# Generated by Django 5.1.3 on 2024-11-19 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_video', models.FileField(upload_to='videos/')),
                ('extracted_audio_file', models.FileField(upload_to='audio/')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
            ],
        ),
    ]
