# Generated by Django 5.1.3 on 2024-11-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_Extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='extracted_audio_file',
            field=models.FileField(default=None, upload_to='audio/'),
        ),
    ]
