# Generated by Django 5.1.3 on 2024-11-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_Extraction', '0002_alter_video_extracted_audio_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='original_video',
            new_name='video_file',
        ),
    ]
