# Generated by Django 5.1.3 on 2024-11-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_Extraction', '0004_ytvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=None, upload_to='videos/'),
        ),
    ]
