# Generated by Django 5.1.3 on 2024-11-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_remove_songpreds_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='songpreds',
            name='artist_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='songpreds',
            name='background_image',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='songpreds',
            name='shazam_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
