# Generated by Django 5.1.3 on 2024-11-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_songpreds_artist_name_songpreds_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songpreds',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='songpreds',
            name='shazam_link',
        ),
    ]
