# Generated by Django 5.1.3 on 2024-11-21 06:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Audio_Extraction', '0002_alter_video_extracted_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_file', models.FileField(blank=True, null=True, upload_to='chunks/')),
                ('start_time', models.FloatField(blank=True, null=True)),
                ('spectrogram_image', models.BinaryField(blank=True, null=True)),
                ('labels', models.IntegerField(blank=True, default=None)),
                ('song_prediction', models.CharField(blank=True, default='', max_length=200)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_chunks', to='Audio_Extraction.video')),
            ],
        ),
    ]
