# Generated by Django 5.1.3 on 2024-11-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chunking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiochunk',
            name='labels',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
